
# This workflow file is disabled to prevent conflicts with static.yml
name: Jekyll workflow (disabled)

# This workflow is disabled to avoid conflicts with static.yml
on:
  workflow_dispatch:
    inputs:
      run_disabled:
        description: 'This workflow is disabled'
        required: true
        default: 'false'

jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
      - name: Disabled workflow
        run: echo "This workflow is disabled to prevent conflicts with static.yml"
